feature/mx-1702 resolve types in edit view
robert-koch-institut/mex-admin pull request #158
Opened 2024-09-18 12:48 UTC by cutoffthetop

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-11-13 12:35 UTC, rababerladuseladim requested changes
Only minor nitpicking.

2024-11-13 12:35 UTC, rababerladuseladim commented on CHANGELOG.md
> +- fix routing issues by moving the refresh handlers section.from on_mount to page.on_load
```suggestion
- fix routing issues by moving the refresh handlers section from `on_mount` to `page.on_load`
```

2024-11-13 12:35 UTC, rababerladuseladim commented on mex/editor/components.py
> +    return rx.text(
Where is the language attribute?

2024-11-13 12:35 UTC, rababerladuseladim commented on pyproject.toml
> +    "mex-backend@git+https://github.com/robert-koch-institut/mex-backend.git@0.22.0",
Why does the editor depend on the backend?

2024-11-13 12:35 UTC, rababerladuseladim commented on mex/editor/transform.py
> +    if values is None:
Why doesn't this return the same as `transform_value(None)`?

2024-11-13 12:35 UTC, rababerladuseladim commented on mex/editor/transform.py
> +    return transform_values(models[0].identifier)
Please add a test for the no models and no titles case.

2024-11-13 12:35 UTC, rababerladuseladim commented on tests/test_transform.py
>  def test_render_model_title(dummy_data: list[AnyExtractedModel]) -> None:
```suggestion
def test_transform_models_to_title(dummy_data: list[AnyExtractedModel]) -> None:
```

2024-11-13 12:35 UTC, rababerladuseladim commented on tests/test_transform.py
>  def test_render_model_preview(dummy_data: list[AnyExtractedModel]) -> None:
```suggestion
def test_transform_models_to_preview(dummy_data: list[AnyExtractedModel]) -> None:
```

2024-11-13 12:35 UTC, rababerladuseladim commented on tests/test_transform.py
> +    dummy_previews = [transform_models_to_preview([d]) for d in dummy_data]
please add tests for the no preview / no models case.

2024-11-13 12:35 UTC, rababerladuseladim commented on tests/conftest.py
> +class ResettingGraphConnector(GraphConnector):
Meh, any idea how to not depend on mex-backend here?

2024-11-14 10:24 UTC, cutoffthetop commented on pyproject.toml
> +    "mex-backend@git+https://github.com/robert-koch-institut/mex-backend.git@0.22.0",
it's a dev-dependency because i'm re-using the graph connector in the tests

2024-11-14 10:25 UTC, cutoffthetop commented on mex/editor/components.py
> +    return rx.text(
doc fixed c63dde7

2024-11-14 10:35 UTC, cutoffthetop commented on tests/conftest.py
> +class ResettingGraphConnector(GraphConnector):
we could move this to mex-common as an extra? a la `pip install mex-common[graph]`

2024-11-14 10:58 UTC, cutoffthetop commented on mex/editor/transform.py
> +    if values is None:
fixed in 7fbb1c5 and tested in ec64850

2024-11-14 11:11 UTC, cutoffthetop commented on mex/editor/transform.py
> +    return transform_values(models[0].identifier)
i added a simple no-models test. no-titles was already covered below, but i added comments in d6beb76

2024-11-14 11:13 UTC, cutoffthetop commented on tests/test_transform.py
> +    dummy_previews = [transform_models_to_preview([d]) for d in dummy_data]
550a942

2024-11-14 11:17 UTC, cutoffthetop commented on tests/conftest.py
> +class ResettingGraphConnector(GraphConnector):
if you see that as an option too, i'd like to push it to a new ticket though. i drafted MX-1746, so we can discuss in refinement

2024-11-14 12:26 UTC, rababerladuseladim approved these changes

2024-11-14 12:26 UTC, merged