feature/mx-1649 prevent and subtract
robert-koch-institut/mex-admin pull request #192
Opened 2024-11-11 08:18 UTC by cutoffthetop

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2025-01-20 13:58 UTC, rababerladuseladim requested changes
wow...

2025-01-20 13:58 UTC, rababerladuseladim commented on tests/conftest.py
> +            monkeypatch.setattr(settings, "identity_provider", IdentityProvider.MEMORY)
There should only be one settings instance. I am however surprised that this does not throw an error in mex common...

```suggestion
    settings = EditorSettings.get():    
    if is_integration_test:
        monkeypatch.setitem(settings.model_config, "validate_assignment", False)
        monkeypatch.setattr(
            settings, "identity_provider", EditorIdentityProvider.BACKEND
        )
    else:
        monkeypatch.setattr(settings, "identity_provider", IdentityProvider.MEMORY)
```

2025-01-20 13:58 UTC, rababerladuseladim commented on tests/conftest.py
> +    flush_graph_database: None,  # noqa: ARG001
Why not `pytest.usefixture`?

2025-01-20 13:58 UTC, rababerladuseladim commented on mex/editor/edit/main.py
> +        on_change=lambda enabled: cast(EditState, EditState).toggle_field_value(
why is casting required here?

2025-01-20 13:58 UTC, rababerladuseladim commented on mex/editor/transform.py
>              text=str(value),
```suggestion
            text=value,
```

2025-01-20 13:58 UTC, rababerladuseladim commented on mex/editor/edit/transform.py
> +        )
I struggled to understand when this condition is met. Could you introduce a speaking variable for it? E.g. `model_value_is_merbeable_and_subtracted_by_rule`?

2025-01-20 13:58 UTC, rababerladuseladim commented on mex/editor/edit/transform.py
> +                    ),
same for this. `field_is_mergeable_and_prevented_by_rule`

2025-01-20 13:58 UTC, rababerladuseladim commented on mex/editor/identity.py
> +    @cache  # noqa: B019
Why is `B019` safe to ignore? Because BackendIdentityProvider is a singleton? If yes, could you add that to the comment?

2025-01-20 13:58 UTC, rababerladuseladim commented on tests/edit/test_main.py
> +def test_edit_page_switch_roundtrip(
wow, what a journey O.O

2025-01-21 08:33 UTC, cutoffthetop commented on mex/editor/identity.py
> +    @cache  # noqa: B019
done 588f5fa

2025-01-21 08:34 UTC, cutoffthetop commented on mex/editor/transform.py
>              text=str(value),
it might still be a `str` subclass after the `isinstance` check, like `Email`

2025-01-21 08:38 UTC, cutoffthetop commented on mex/editor/edit/main.py
> +        on_change=lambda enabled: cast(EditState, EditState).toggle_field_value(
mypy complains about `toggle_field_value` being an instance method, not a class method. meanwhile, reflex is doing some dark singleton magic with States, so that this method is actually being called on the singleton instance during runtime

2025-01-21 08:47 UTC, cutoffthetop commented on tests/conftest.py
> +    flush_graph_database: None,  # noqa: ARG001
that doesn't work and would fail https://docs.astral.sh/ruff/rules/pytest-erroneous-use-fixtures-on-fixture

> Note this mark [usefixture] has no effect in fixture functions

see, https://docs.pytest.org/en/8.3.x/how-to/fixtures.html

2025-01-21 09:12 UTC, cutoffthetop commented on mex/editor/edit/transform.py
> +        )
i simplified it a bit (the subtractive argument didn't actually have to be optional), and added some comments: a66e32d

2025-01-21 09:12 UTC, cutoffthetop commented on mex/editor/edit/transform.py
> +                    ),
see also a66e32d

2025-01-21 09:15 UTC, cutoffthetop commented on tests/conftest.py
> +            monkeypatch.setattr(settings, "identity_provider", IdentityProvider.MEMORY)
you're right. both `BaseSettings.get()` and `EditorSettings.get()` returned the same `EditorSettings` instance, and the loop would just do the same thing twice 🤦

2025-01-22 08:25 UTC, rababerladuseladim approved these changes

2025-01-22 09:15 UTC, merged