feature/mx-1347 link cruft template
robert-koch-institut/mex-admin pull request #6
Opened 2024-01-11 09:58 UTC by cutoffthetop

2024-01-17 12:26 UTC, rababerladuseladim requested changes
Miniminor stuff.

2024-01-17 12:26 UTC, rababerladuseladim commented on CHANGELOG.md
> +# Changelog
Please add your changes.

2024-01-17 12:26 UTC, rababerladuseladim commented on README.md
> +[![linting](https://github.com/robert-koch-institut/mex-editor/actions/workflows/linting.yml/badge.svg)](https://github.com/robert-koch-institut/mex-editor/actions/workflows/linting.yml)
Oh...

2024-01-17 13:35 UTC, cutoffthetop commented on README.md
> +[![linting](https://github.com/robert-koch-institut/mex-editor/actions/workflows/linting.yml/badge.svg)](https://github.com/robert-koch-institut/mex-editor/actions/workflows/linting.yml)
yeah 😅

2024-01-17 13:35 UTC, cutoffthetop commented on CHANGELOG.md
> +# Changelog
done 17c22d4

2024-01-18 08:43 UTC, rababerladuseladim approved these changes

2024-01-18 08:55 UTC, merged