feature/reflex
robert-koch-institut/mex-admin pull request #75
Opened 2024-06-04 11:45 UTC by cutoffthetop

# PR Context

- switch tech stack to python/reflex

2024-06-07 09:08 UTC, rababerladuseladim requested changes
biutiful. Thank you very much for this beautiful new editor prototype!

2024-06-07 09:08 UTC, rababerladuseladim commented on README.md
>  - push `git push --follow-tags`
```suggestion
- run `pdm release RULE` to release a new version where RULE determines which part of
  the version to update and is one of `major`, `minor`, `patch`.
```

2024-06-07 09:08 UTC, rababerladuseladim commented on mex/editor/transform.py
> +        return obj.__pydantic_serializer__.to_python(
Why not:
```suggestion
        return obj.model_dump(
```
?

2024-06-07 09:08 UTC, rababerladuseladim commented on pyproject.toml
> +venv = ".venv"
Who is using pyright and why?

2024-06-10 10:21 UTC, cutoffthetop commented on pyproject.toml
> +venv = ".venv"
ups, not me. 1188acc

2024-06-10 10:27 UTC, cutoffthetop commented on mex/editor/transform.py
> +        return obj.__pydantic_serializer__.to_python(
added a reason here: 82e2777

2024-06-13 13:27 UTC, merged